### ISSUE TITLE
建议把这里修改一下

### ISSUE THREAD

**Issue by Alafun** [Misakago/ah_youth_study#1]
```git
# SECURITY WARNING: keep the secret key used in production secret!

```

这个[地方](https://github.com/Misakago/ah_youth_study/blob/c39b88581dc493de187d77c0543d69d9045b095d/youthStudy/settings.py#L23-L24)

详情可以看[这个链接](https://docs.github.com/cn/actions/security-guides/encrypted-secrets)

**Comment by Misakago** [comment]
谢谢你的反馈
